import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PromotionBar from '@/components/PromotionBar'
import Footer from '@/components/Footer'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id='root' className={inter.className}>
        <PromotionBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
